### ISSUE TITLE
netty first websocket handshake and then protobuf exchange

### ISSUE THREAD

**Issue by SameerTi** [jiayanguo/nettyprotobufapp#1]
Hi @jiayanguo  
could you please share an example, where first a webSocket handshake takes place between the WebSocketClient and WebScoketServer and upon success, protobuf msgs are exchanged ?

Thanks in Advance!

**Comment by jiayanguo** [comment]
@SameerTi Here is the netty+websocket+protobuf example. Let me know how it goes.

Server:
https://github.com/jiayanguo/nettyprotobufapp/blob/master/server/src/main/java/org/demo/nettyprotobuf/websocket/server/DemoWsServer.java

Client: https://github.com/jiayanguo/nettyprotobufapp/blob/master/client/src/main/java/org/demo/nettyprotobuf/websocket/server/client/DemoClient.java
